### ISSUE TITLE
Maven issue on resolving dep's

### ISSUE THREAD

**Issue by fils** [sindice/sparqled#1]
Very interested in trying this out on our virtuoso server.   Tried the:

mvn --projects sparql-summary package assembly:assembly --also-make

and got

[ERROR] Failed to execute goal on project sesame-backend: Could not resolve dependencies for project org.sindice.core:sesame-backend:jar:0.9: The following artifacts could not be resolved: virtuoso.sesame2.driver:virt_sesame2:jar:1.0, virtuoso.jdbc3:virtjdbc3:jar:1.0: Failure to find virtuoso.sesame2.driver:virt_sesame2:jar:1.0 in file:///Users/dfils/src/git/sparqled/sesame-backend/../lib/ was cached in the local repository, resolution will not be reattempted until the update interval of virtuoso has elapsed or updates are forced -> [Help 1]

thought I would post it here in case it was of use.

**Comment by sindice** [comment]
Hi Douglas,

thanks you for your feedback!

I forgot to commit the virtuoso libraries when I commited the code to github.

However, I was not able to build correctly the project with that maven command only.

As a temporary solution, please run:

   mvn install

before executing:

   mvn --projects sparql-summary package assembly:assembly --also-make

I'll come back to you with a proper solution

Thanks

**Comment by sindice** [comment]
The original mvn command works, it seems the test user account I used was somehow corrupted.
If you still have an issue, remove the virtuoso folder in you local maven repository (~/.m2/repository) and this should do it.

**Comment by fils** [comment]
Sorry for the delay..   all is building fine!  
Thanks Doug

**Comment by sindice** [comment]
Perfect ;o)

Thanks for the report
