### ISSUE TITLE
Remove Sindice_home from the webapps setup

### ISSUE THREAD

**Issue by scampi** [sindice/sparqled#17]
sindice_home made sense in the sindice environment where there were potentially many webapps running. In this project, this is not necessary.

**Comment by sindice** [comment]
Updated code to specify only a `sparqled/home` parameter.

``` xml
<Context docBase="/path/to/sparqled.war">
    <Parameter name="sparqled/home" value="/path/to/sparqled/home" override="false" />
</Context>
```
