### ISSUE TITLE
syntax error at 'GROUP_CONCAT'

### ISSUE THREAD

**Issue by fils** [sindice/sparqled#2]
I was able to build the package fine.   I then moved to build the DGS with:

java -Xmx2048m -cp target/sparql-summary-assembly.jar org.sindice.summary.Pipeline --type HTTP --repository http://data.oceandrilling.org/sparql --outputfile ~/tmp/summary.nt.gz

However, I get several similar errors from my Virtuoso (version 6.4  ..  I got an early build from them to address a SPARQL federation issue).  

11:30:20.275 [main] WARN  org.openrdf.http.client.HTTPClient - Server reports problem: Virtuoso 37000 Error SP030: SPARQL compiler, line 12: syntax error at 'GROUP_CONCAT' before '('

All the errors occur at line 12 with the following being one of the failed SPARQL calls:

SPARQL query:
PREFIX sindice: http://vocab.sindice.net/
PREFIX rdf: http://www.w3.org/1999/02/22-rdf-syntax-ns#
PREFIX og: http://opengraphprotocol.org/schema/
PREFIX ogp: http://ogp.me/ns#
PREFIX ogorg: http://opengraph.org/schema/
PREFIX dc: http://purl.org/dc/elements/1.1/
PREFIX dbp: http://dbpedia.org/property/
PREFIX voca: http://vocab.sindice.net/analytics#
SELECT ?label ?pType ?pDescription (COUNT (?s) AS ?cardinality)
WHERE {
{
SELECT ?s (GROUP_CONCAT(IF(isURI(?type),
           concat('{<', str(?type), '>,',?p,'}'),
           concat('{"', ENCODE_FOR_URI(?type), '",',?p,'}'))) AS ?label)
        WHERE {
        {
            SELECT ?s ?type ?p WHERE
            {
{ ?s rdf:type ?type .
  BIND ('0' AS ?p) }
UNION{ ?s og:type ?type .
 BIND ('1' AS ?p) }
UNION{ ?s ogp:type ?type .
 BIND ('2' AS ?p) }
UNION{ ?s ogorg:type ?type .
 BIND ('3' AS ?p) }
UNION{ ?s dc:type ?type .
 BIND ('4' AS ?p) }
UNION{ ?s dbp:type ?type .
 BIND ('5' AS ?p) }
UNION{ ?s voca:type ?type .
 BIND ('6' AS ?p) }
            }
            ORDER BY ?type
        }
        }
        GROUP BY ?s
    }
FILTER(?label != "")
}
GROUP BY ?label ?pType ?pDescription

**Comment by sindice** [comment]
Could you pull the latest changes. Now, you should write `--type VIRTUOSO` instead of `HTTP`.
The virtuoso requires a specific syntax for this query, e.g., the Group_concat or the bind (the bind is not supported by virtuoso).

**Comment by fils** [comment]
did a git pull and got the latest changes and rebuilt..   

using --type VIRTUOSO seems to be working (no errors)..   building summary is taking a long time (> 3 hours so far)  Likely it's a long process though?

FYI
I did --type virtuoso (small case) first and got an error..    upper case I guess is required..  however the error did not list VIRTUOSO as an option 

2012-07-05 14:24:16,400 [main] ERROR org.sindice.summary.pipeline - You need to define the type of the local repository (SQL, NATIVE, MEMORY or HTTP)

**Comment by sindice** [comment]
Yes, depending on the size (number of triples in general) of the data you
want to compute the summary on, the required time may vary.
How much memory did you give to the jvm ? Increasing it can help also

We'll correct the error message, thanks for the report.

On Fri, Jul 6, 2012 at 4:04 PM, Douglas Fils <
reply@reply.github.com

**Comment by fils** [comment]
I gave it the recommended 2048..   seems to be running fine though..  I will just let it go and see what it does.  Looking forward to trying this out.      I'll report back when it completes..
